// AUTO-GENERATED by scripts/generate-models.ts — do not edit manually.
import type { Model, Api } from "./types.js";

export const models: Model<Api>[] = [
  {
    id: "gpt-4o",
    name: "GPT-4o",
    api: "azure-openai-completions",
    provider: "azure-openai",
    baseUrl: "",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 2.5,
      output: 10,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 16384,
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    api: "azure-openai-completions",
    provider: "azure-openai",
    baseUrl: "",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.15,
      output: 0.6,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 16384,
  },
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    api: "azure-openai-completions",
    provider: "azure-openai",
    baseUrl: "",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 2,
      output: 8,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1047576,
    maxTokens: 32768,
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    api: "azure-openai-completions",
    provider: "azure-openai",
    baseUrl: "",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.4,
      output: 1.6,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1047576,
    maxTokens: 32768,
  },
  {
    id: "gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    api: "azure-openai-completions",
    provider: "azure-openai",
    baseUrl: "",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.1,
      output: 0.4,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 1047576,
    maxTokens: 32768,
  },
  {
    id: "gpt-5.4-mini",
    name: "GPT-5.4 Mini",
    api: "azure-openai-responses",
    provider: "azure-openai",
    baseUrl: "",
    reasoning: true,
    thinkingLevelMap: { none: null, short: 40000, medium: 80000, long: 100000 },
    input: ["text", "image"],
    cost: {
      input: 0.75,
      output: 4.5,
      cacheRead: 0.075,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 128000,
  },
  {
    id: "gpt-5.4-nano",
    name: "GPT-5.4 Nano",
    api: "azure-openai-responses",
    provider: "azure-openai",
    baseUrl: "",
    reasoning: true,
    thinkingLevelMap: { none: null, short: 40000, medium: 80000, long: 100000 },
    input: ["text", "image"],
    cost: {
      input: 0.2,
      output: 1.25,
      cacheRead: 0.02,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 128000,
  },
  {
    id: "o1",
    name: "o1",
    api: "azure-openai-completions",
    provider: "azure-openai",
    baseUrl: "",
    reasoning: true,
    thinkingLevelMap: { none: null, short: 40000, medium: 80000, long: 100000 },
    input: ["text", "image"],
    cost: {
      input: 15,
      output: 60,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 200000,
    maxTokens: 100000,
  },
  {
    id: "o1-mini",
    name: "o1-mini",
    api: "azure-openai-completions",
    provider: "azure-openai",
    baseUrl: "",
    reasoning: true,
    thinkingLevelMap: { none: null, short: 30000, medium: 50000, long: 65536 },
    input: ["text"],
    cost: {
      input: 3,
      output: 12,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 128000,
    maxTokens: 65536,
  },
  {
    id: "o3-mini",
    name: "o3-mini",
    api: "azure-openai-completions",
    provider: "azure-openai",
    baseUrl: "",
    reasoning: true,
    thinkingLevelMap: { none: null, short: 40000, medium: 80000, long: 100000 },
    input: ["text", "image"],
    cost: {
      input: 1.1,
      output: 4.4,
      cacheRead: 0,
      cacheWrite: 0,
    },
    contextWindow: 200000,
    maxTokens: 100000,
  },
];

const modelMap = new Map(models.map((m) => [m.id, m]));

export function getModel(id: string): Model<Api> | undefined {
  return modelMap.get(id);
}

export function listModels(): Model<Api>[] {
  return models;
}

export function getModelsByProvider(provider: string): Model<Api>[] {
  return models.filter((m) => m.provider === provider);
}
