// AUTO-GENERATED by scripts/generate-models.ts — do not edit manually.
import type { Model, Api } from "./types.js";

export const models: Model<Api>[] = [
  {
    id: "gpt-5.4-nano",
    name: "GPT-5.4 Nano",
    api: "azure-openai-completions",
    provider: "azure-openai",
    baseUrl: "",
    reasoning: false,
    input: ["text", "image"],
    cost: {
      input: 0.2,
      output: 1.25,
      cacheRead: 0.02,
      cacheWrite: 0,
    },
    contextWindow: 400000,
    maxTokens: 128000,
  },
];

const modelMap = new Map(models.map((m) => [m.id, m]));

export function getModel(id: string): Model<Api> | undefined {
  return modelMap.get(id);
}

export function listModels(): Model<Api>[] {
  return models;
}

export function getModelsByProvider(provider: string): Model<Api>[] {
  return models.filter((m) => m.provider === provider);
}
